FROM node:22-bookworm-slim

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 7070

CMD ["npx", "ts-node-dev", "--respawn", "--poll", "--transpile-only", "--require", "tsconfig-paths/register", "src/app.ts"]
